### ISSUE TITLE
KeyError: 'SIGUSR1'

### ISSUE THREAD

**Issue by estevaofuzaro98** [ThGaskin/NeuralABM#31]
Hello everyone!

I apologize in advance as I am fairly new to the GitHub universe. I followed the step-by-step instructions described in the README file, including cloning the repository and installing the necessary packages. However, for some reason, I am receiving the following error when running the code: `utopya projects register . --with-models`.

Below, I present the log with the error `KeyError: 'SIGUSR1'`.
```
PS D:\Documents\GitHub\NeuralABM> utopya projects register . --with-models
Traceback (most recent call last):
  File "C:\Users\Microsoft Windows\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Microsoft Windows\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Microsoft Windows\AppData\Local\Programs\Python\Python310\Scripts\utopya.exe\__main__.py", line 7, in <module>
  File "C:\Users\Microsoft Windows\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Microsoft Windows\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Microsoft Windows\AppData\Local\Programs\Python\Python310\lib\site-packages\utopya_cli\projects.py", line 229, in register  
    import utopya
  File "C:\Users\Microsoft Windows\AppData\Local\Programs\Python\Python310\lib\site-packages\utopya\__init__.py", line 80, in <module>       
    from .model import Model
  File "C:\Users\Microsoft Windows\AppData\Local\Programs\Python\Python310\lib\site-packages\utopya\model.py", line 17, in <module>
    from .multiverse import FrozenMultiverse, Multiverse
  File "C:\Users\Microsoft Windows\AppData\Local\Programs\Python\Python310\lib\site-packages\utopya\multiverse.py", line 28, in <module>     
    from .workermanager import WorkerManager
  File "C:\Users\Microsoft Windows\AppData\Local\Programs\Python\Python310\lib\site-packages\utopya\workermanager.py", line 25, in <module>  
    -SIGMAP[SIG_STOPCOND],
KeyError: 'SIGUSR1'
```

I have no idea what this error is or how to solve it. I tried to research it on my own in the documentation, but had to resort to asking for help here (I don't even know if I did it correctly). Thank you in advance!

Edit: I use Microsoft Visual Studio Code.

**Comment by ThGaskin** [comment]
Hiya, 

thanks for letting us know. We don't test utopya on Windows installations, so I'm not immediately sure what this could be. But you are installing everything into a conda/pip virtual environment, I'm assuming? Does the installation of the required packages complete without errors? And what happens when you do e.g. `utopya --help` from within the venv?

**Comment by estevaofuzaro98** [comment]
Thank you for the fast response, Gaskin, and I also wanted to congratulate you on your paper in PNAS. It is amazing! 😁

I did not encounter any issues while installing the libraries. I was able to successfully install `utopya` as well.
And there are no error logs when I enter `utopya --help` in the Terminal, as can be seen below:
```
PS D:\Documents\GitHub\NeuralABM> utopya --help
Usage: utopya [OPTIONS] COMMAND [ARGS]...
Options:
  --help  Show this message and exit.
Commands:
  batch     Run and evaluate multiple simulations.
  config    Read and modify the utopya configuration.
  eval      Evaluate a previously finished simulation run.
  models    Show available models and register new ones.
  projects  Show available projects and register new ones.
  run       Perform a simulation run and evaluate its outputs.
  test      Run the Python model tests associated with the specified model.
  Copyright (C) 2018 – 2023  utopya developers
  utopya is free software and comes with absolutely no warranty. You are
  welcome to redistribute it under the conditions specified in the LGPLv3+
  license. For more information, visit:
     utopia-project.org  |  gitlab.com/utopia-project/utopya
PS D:\Documents\GitHub\NeuralABM>
```
And as can be seen above the library runs fine even in different partitions. I have never had problems running `.py` programs on another partition.

I'm thinking about running it on my desktop with Windows to check if the problem persists. 🤔
So maybe the issue could be with my laptop.

Thank you in advance.

**Comment by ThGaskin** [comment]
Which version of utopya are you using? (`pip freeze`)

And do you get the same error if you just do
`utopya projects register .`?

On 31. Mar 2023, at 01:53, Estevão Fuzaro ***@***.***> wrote:

﻿

Thank you for the fast response, Gaskin, and I also wanted to congratulate you on your paper in PNAS. It is amazing! 😁

I did not encounter any issues while installing the libraries. I was able to successfully install utopya as well.
And there are no error logs when I enter utopya --help in the Terminal, as can be seen below:

PS D:\Documents\GitHub\NeuralABM> utopya --help
Usage: utopya [OPTIONS] COMMAND [ARGS]...
Options:
  --help  Show this message and exit.
Commands:
  batch     Run and evaluate multiple simulations.
  config    Read and modify the utopya configuration.
  eval      Evaluate a previously finished simulation run.
  models    Show available models and register new ones.
  projects  Show available projects and register new ones.
  run       Perform a simulation run and evaluate its outputs.
  test      Run the Python model tests associated with the specified model.
  Copyright (C) 2018 – 2023  utopya developers
  utopya is free software and comes with absolutely no warranty. You are
  welcome to redistribute it under the conditions specified in the LGPLv3+
  license. For more information, visit:
     utopia-project.org  |  gitlab.com/utopia-project/utopya
PS D:\Documents\GitHub\NeuralABM>


And as can be seen above the library runs fine even in different partitions. I have never had problems running .py programs on another partition.

I'm thinking about running it on my desktop with Windows to check if the problem persists. 🤔
So maybe the issue could be with my laptop.

Thank you in advance.

**Comment by blsqr** [comment]
Hi @estevaofuzaro98, and thank you for opening the issue :)

I'm afraid, utopya does not currently support Windows, exactly due to the situation you encountered: On Unix systems (Linux, macOS), there is a certain way of communicating with processes via so-called "signals". These signals differ on Windows and are currently not compatible.

Unfortunately, there is nothing you can do at this moment to get around this restriction (unless you want to run this model in [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install)). However, I opened an issue over at [utopya](https://gitlab.com/utopia-project/utopya/-/issues/78) to address this and hopefully add Windows compatibility.

**Comment by estevaofuzaro98** [comment]
Thank you for your support, guys! @ThGaskin @blsqr 
I will try to dual-boot my laptop for now until Windows is supported.
Best regards!

**Comment by estevaofuzaro98** [comment]
Hey guys! Just an update.

I performed the WSL installation, as suggested by @blsqr, and was able to run it without problems via Visual Studio Code.

The only thing I had to dig a little deeper into was the LaTeX fonts.
I found the proper solutions by installing
`sudo apt-get install texlive-latex-extra texlive-fonts-recommended dvipng cm-super`
and also
`pip install latex`

Maybe include these in `requirements.txt`?

Anyway, I managed to reproduce the simulations!
Thanks a lot for the support again.

**Comment by ThGaskin** [comment]
Thanks! Good to hear it's working :)

Latex shouldn't be a requirement for installation -- I guess I'm still using the `text.usetex: True` rcParam somewhere ... I'll turn that off. Thanks for letting me know!

**Comment by zhongdigood** [comment]
May I ask if you have successfully reproduced the simulation on the windows system? How?

**Comment by estevaofuzaro98** [comment]
@zhongdigood

Hello! I am running on a virtual Linux machine via [WSL2](https://learn.microsoft.com/en-us/windows/wsl/install).
Also, I am using Visual Studio Code to run. There is [support](https://code.visualstudio.com/docs/remote/wsl) to WSL inside VSCode.

I was able to reproduce the results by doing this procedure.
Any questions, just let me know.
Best regards!

**Comment by ThGaskin** [comment]
We are currently working on making utopya support windows, but it might take a while. You can track its progress [here](https://gitlab.com/utopia-project/utopya/-/issues/78)

**Comment by zhongdigood** [comment]
@estevaofuzaro98 
Thank you very much!
**When I run "utopya run SIR" on Ubuntu, I get the following error:**

```INFO     run               Parsing additional command line arguments ...
NOTE     run               Updates to meta configuration:

{debug_level: 0}

REMARK   entry             Getting info bundle for model 'SIR' ...
REMARK   entry               ... selecting only registered info bundle:  from_manifest_file
PROGRESS model             Initializing Model instance for 'SIR' ...
NOTE     model               Project:        NeuralABM
NOTE     model               Framework:      None
PROGRESS multiverse        Initializing Multiverse for 'SIR' model ...
INFO     multiverse        Building meta-configuration ...
NOTE     multiverse        Run configuration:
  /home/weipeng/NeuralABM-main/NeuralABM/models/SIR/SIR_cfg.yml
INFO     multiverse        Built meta configuration.
REMARK   multiverse          Debug level:  0
NOTE     multiverse        Run directory:
  /home/weipeng/utopya_output/SIR/230607-134706
INFO     multiverse        Performing backups ...
NOTE     multiverse          Backed up meta configuration.
NOTE     multiverse          Backed up full parameter space and metadata.
NOTE     multiverse          Backed up all involved configuration files.
WARNING  gitinfo           No git dir found
NOTE     multiverse          Stored project's git info and patch.
INFO     multiverse        Validating 13 parameters ...
REMARK   multiverse        Parameter space volume:      0
NOTE     multiverse        All parameters valid.
Traceback (most recent call last):
  File "/home/weipeng/env1/bin/utopya", line 8, in <module>
    sys.exit(cli())
  File "/home/weipeng/env1/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/weipeng/env1/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/weipeng/env1/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/weipeng/env1/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/weipeng/env1/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/weipeng/env1/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/weipeng/env1/lib/python3.10/site-packages/utopya_cli/run.py", line 199, in run
    mv = model.create_mv(run_cfg_path=run_cfg, **update_dict)
  File "/home/weipeng/env1/lib/python3.10/site-packages/utopya/model.py", line 298, in create_mv
    mv = Multiverse(
  File "/home/weipeng/env1/lib/python3.10/site-packages/utopya/multiverse.py", line 189, in __init__
    self._prepare_executable(**self.meta_cfg["executable_control"])
  File "/home/weipeng/env1/lib/python3.10/site-packages/utopya/multiverse.py", line 1074, in _prepare_executable
    raise PermissionError(
PermissionError: The specified executable path for model 'SIR' does not point to an executable file. Did you set the correct access rights? Use chmod to adjust access rights.
Executable path:  {execpath}`

**Comment by ThGaskin** [comment]
Try doing 

```shell
chmod +x path/to/run.py
``` 
?

**Comment by zhongdigood** [comment]
@ThGaskin 
Thanks! But there are still some problems.

```(env1) ➜  NeuralABM-main utopya run SIR       
INFO     run               Parsing additional command line arguments ...
NOTE     run               Updates to meta configuration:

{debug_level: 0}

REMARK   entry             Getting info bundle for model 'SIR' ...
REMARK   entry               ... selecting only registered info bundle:  from_manifest_file
PROGRESS model             Initializing Model instance for 'SIR' ...
NOTE     model               Project:        NeuralABM
NOTE     model               Framework:      None
PROGRESS multiverse        Initializing Multiverse for 'SIR' model ...
INFO     multiverse        Building meta-configuration ...
NOTE     multiverse        Using default run configuration:
  /home/weipeng/NeuralABM-main/models/SIR/SIR_cfg.yml

INFO     multiverse        Built meta configuration.
REMARK   multiverse          Debug level:  0
NOTE     multiverse        Run directory:
  /home/weipeng/utopya_output/SIR/230607-200005
INFO     multiverse        Performing backups ...
NOTE     multiverse          Backed up meta configuration.
NOTE     multiverse          Backed up full parameter space and metadata.
NOTE     multiverse          Backed up all involved configuration files.
WARNING  gitinfo           Git repository is broken (no head ref file)
Traceback (most recent call last):
  File "/home/weipeng/env1/bin/utopya", line 8, in <module>
    sys.exit(cli())
  File "/home/weipeng/env1/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/weipeng/env1/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/weipeng/env1/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/weipeng/env1/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/weipeng/env1/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/weipeng/env1/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/weipeng/env1/lib/python3.10/site-packages/utopya_cli/run.py", line 199, in run
    mv = model.create_mv(run_cfg_path=run_cfg, **update_dict)
  File "/home/weipeng/env1/lib/python3.10/site-packages/utopya/model.py", line 298, in create_mv
    mv = Multiverse(
  File "/home/weipeng/env1/lib/python3.10/site-packages/utopya/multiverse.py", line 172, in __init__
    self._perform_backup(
  File "/home/weipeng/env1/lib/python3.10/site-packages/utopya/multiverse.py", line 964, in _perform_backup
    prj_info = prj.get_git_info(include_patch_info=True)
  File "/home/weipeng/env1/lib/python3.10/site-packages/utopya/project_registry.py", line 141, in get_git_info
    info = gitinfo.get_git_info(base_dir)
  File "/home/weipeng/env1/lib/python3.10/site-packages/gitinfo/gitinfo.py", line 120, in get_git_info
    return get_git_info_dir(gitdir)
  File "/home/weipeng/env1/lib/python3.10/site-packages/gitinfo/gitinfo.py", line 77, in get_git_info_dir
    head_commit, refs = get_head_commit(directory)
  File "/home/weipeng/env1/lib/python3.10/site-packages/gitinfo/gitinfo.py", line 61, in get_head_commit
    remotes = os.listdir(remotes_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/weipeng/.git/refs/remotes'`

**Comment by zhongdigood** [comment]
@ThGaskin 
**Now it works, although the git warnings are still there. Is it reasonable to run "utopya run SIR" with the following results?**
```  uni0 out:  PROGRESS    Completed epoch 320 / 1000;    current loss: 0.3333333432674408
  uni0 out:  PROGRESS    Completed epoch 321 / 1000;    current loss: 0.3333333432674408
  uni0 out:  PROGRESS    Completed epoch 322 / 1000;    current loss: 0.3333333432674408
  uni0 out:  PROGRESS    Completed epoch 323 / 1000;    current loss: 0.3333333432674408
  uni0 out:  PROGRESS    Completed epoch 324 / 1000;    current loss: 0.3333333432674408
  uni0 out:  PROGRESS    Completed epoch 325 / 1000;    current loss: 0.3333333432674408
  uni0 out:  PROGRESS    Completed epoch 326 / 1000;    current loss: 0.3333333432674408
  uni0 out:  PROGRESS    Completed epoch 327 / 1000;    current loss: 0.3333333432674408
  uni0 out:  PROGRESS    Completed epoch 328 / 1000;    current loss: 0.3333333432674408
  uni0 out:  PROGRESS    Completed epoch 329 / 1000;    current loss: 0.3333333432674408
  uni0 out:  PROGRESS    Completed epoch 330 / 1000;    current loss: 0.3333333432674408
......
  uni0 out:  PROGRESS    Completed epoch 996 / 1000;    current loss: 0.3333333432674408
  uni0 out:  PROGRESS    Completed epoch 997 / 1000;    current loss: 0.3333333432674408
  uni0 out:  PROGRESS    Completed epoch 998 / 1000;    current loss: 0.3333333432674408
  uni0 out:  PROGRESS    Completed epoch 999 / 1000;    current loss: 0.3333333432674408
  uni0 out:  PROGRESS    Completed epoch 1000 / 1000;    current loss: 0.3333333432674408
  uni0 out:  PROGRESS    Generating predicted dataset ...
  uni0 out:  INFO    Simulation run finished.
  uni0 out:  INFO    Wrapping up ...
  uni0 out:  SUCCESS    All done.

**Comment by zhongdigood** [comment]
**The "chmod command" you suggested works great! As for the problem of the main branch, the results I obtained by running "git branch -r" are as follows:**
```  
  origin/Cambridge_dataset
  origin/Powergrid_simulations
  origin/gh-pages
  origin/main`

**Comment by ThGaskin** [comment]
Yes, those are the results you get for just running `utopya run SIR`. The default ABM settings produce relative boring dynamics -- a single agent is infected, the cascade spreads quickly, and that's it. Your resulting densities plot should look something like this:

![densities](https://github.com/ThGaskin/NeuralABM/assets/22022754/b5063946-6faa-46c9-9bcf-142609566a3f)

You can adjust the infection radius (`r_infectious`), infection times and other parameters to change the epidemic dynamics.

To reproduce the plots from the paper, run 

`utopya run SIR --cs Predictions`

Also take a look at the `ABM_data` configuration set: this set will produce ABM data with more 'interesting dynamics'. Run it by calling

`utopya run SIR --cs ABM_data`.

You can then use the data generated to produce new predictions (just point the `load_from_dir` entry to the .h5 file you just created). 

I suggest we move any other problems to a separate issue.

**Comment by ThGaskin** [comment]
For the git warnings, did you try the resetting command? What is the terminal output?

**Comment by ThGaskin** [comment]
Update: NeuralABM can now be run on Windows -- see README.
