### ISSUE TITLE
General qs! 

### ISSUE THREAD

**Issue by reggie55** [ThGaskin/NeuralABM#36]
Sorry not an issue but more of a general question!

I am a bit confused with the transition from the continuous probabilities referenced in the paper to the discrete probabilities evaluated. It seems here for the probabilities of the parameters at each iteration, you use the loss function to compute a discrete probability value. For the marginals of a parameter x, you bin the x values, sum over their probabilities, normalize, and then smooth, and then this is our approximation to the posterior distribution of that parameter. Is that correct? 

Also just to check, you are assuming that the error in the time series from the ABM model with the NN's parameters and the true time series is normally distributed? Thanks so much!

**Comment by ThGaskin** [comment]
Glad to hear! :) Do let me know if you need help getting the code to run
