### ISSUE TITLE
How to implement a model?

### ISSUE THREAD

**Issue by estevaofuzaro98** [ThGaskin/NeuralABM#60]
Hello, after just over a year I'm back here to update you on a few things.

First of all, I'd like to say that I've managed to get Utopya to work on Windows, thanks to the fantastic work you've done with the README, which is much more detailed and even has a certain "toy problem" to evaluate the influence of the parameters.

Despite all this, I'm still having trouble implementing my model. The part I find most difficult is building the functions in as much detail as you do. And I feel that what I have to solve is something much simpler to implement, but I don't know exactly how. Could you help me?

To illustrate: I have displacement, velocity and acceleration data for a viscoelastic material that has undergone an impact test (a mass was dropped on this material and it was evaluated how it reacted to this impact from different heights using data from a very high fps camera); there were three different heights and each one had three mass drops, for a total of 9 realizations. I also have a differential equation model of this system and I would like to calibrate the parameters of this model so that they agree (or not) with the experimental data. Basically, I would like to caracterize the material!

When evaluating the SIR/Covid model in this repository, which I believe is the most similar to what I want to do (which would be to evaluate an ODE, train it with measured data and calibrate the parameters) I couldn't find exactly how this whole process is done, that is, in which file/functions the ODE is solved and from what point the parameters are estimated.

I think these are "silly" questions, but I'm really struggling to understand. Although I use Python, I don't have any expertise 😂

Thank you in advance for your attention.
Greetings from Brazil.

**Comment by ThGaskin** [comment]
Hello! Thanks for all your questions :)

So the basic procedure, that almost all the models follow, is 

- Generate or load data: this is usually done in `DataGeneration.py` in the model folders. Here, a function is defined that generates synthetic data or loads data from a file. For SIR, data is generated in `generate_smooth_data`, for example.
- Set up the neural network and train: this is done in `NN.py`. The model ODEs are solved and the neural network trained on the predicted time series data. Training is done in the `epoch` function in `NN.py`. This function actually solves the equations itself -- I think it's better to conceptually separate data generation and training, since you may wish to fit a different model to the data than the one that generated it, but that's up to you
- Then evaluate: this follows the evaluation routine as specified in the [utopia docs](https://docs.utopia-project.org/html/usage/eval/plotting/index.html)

I realise the code is perhaps quite difficult for beginners. I've been thinking about writing a simple Jupyter notebook that just illustrates the method very simply, so you can dive right in without having to install utopya -- do you think that would be of use? 

Best from the UK :)

**Comment by ThGaskin** [comment]
Update: I've added a Jupyter notebook for quick illustration in the main folder; see if it works :)

**Comment by estevaofuzaro98** [comment]
Hi @ThGaskin , thank you very much for taking the time to answer my questions and prepare a notebook. Your commitment to open science is inspiring.

Thank you very much.
I think the whole process will be clearer now! 🎉

**Comment by estevaofuzaro98** [comment]
Hello again.
Indeed the notebook has made everything clearer! Thank you very much in advance.

But, I'm getting a small error when creating the `parameters_ts_xr` variable. From what I've researched, it's something to do with `numpy`.

The cell output generates this:
```
C:\Users\estev\AppData\Local\Temp\ipykernel_33184\1389884034.py:2: FutureWarning: The input object of type 'Tensor' is an array-like implementing one of the corresponding protocols (`__array__`, `__array_interface__` or `__array_struct__`); but not a sequence (or 0-D). In the future, this object will be coerced as if it was first converted using `np.array(obj)`. To retain the old behaviour, you have to either modify the type 'Tensor', or assign to an empty array created with `np.empty(correct_shape, dtype=object)`.
  data=np.array(parameters_ts),
C:\Users\estev\AppData\Local\Temp\ipykernel_33184\1389884034.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  data=np.array(parameters_ts),
```

And the log generates error is this:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[35], [line 1](vscode-notebook-cell:?execution_count=35&line=1)
----> [1](vscode-notebook-cell:?execution_count=35&line=1) parameters_ts_xr = xr.DataArray(
      [2](vscode-notebook-cell:?execution_count=35&line=2)     data=np.array(parameters_ts),
      [3](vscode-notebook-cell:?execution_count=35&line=3)     dims=["batch", "parameter"],
      [4](vscode-notebook-cell:?execution_count=35&line=4)     coords={"batch": np.arange(len(parameters_ts)), "parameter": ["p_infect", "t_infectious"]}
      [5](vscode-notebook-cell:?execution_count=35&line=5) )
      [7](vscode-notebook-cell:?execution_count=35&line=7) parameters_ts_xr.plot.line(hue="parameter");

File [c:\Users\estev\AppData\Local\Programs\Python\Python39\lib\site-packages\xarray\core\dataarray.py:454](file:///C:/Users/estev/AppData/Local/Programs/Python/Python39/lib/site-packages/xarray/core/dataarray.py:454), in DataArray.__init__(self, data, coords, dims, name, attrs, indexes, fastpath)
    [452](file:///C:/Users/estev/AppData/Local/Programs/Python/Python39/lib/site-packages/xarray/core/dataarray.py:452) data = _check_data_shape(data, coords, dims)
    [453](file:///C:/Users/estev/AppData/Local/Programs/Python/Python39/lib/site-packages/xarray/core/dataarray.py:453) data = as_compatible_data(data)
--> [454](file:///C:/Users/estev/AppData/Local/Programs/Python/Python39/lib/site-packages/xarray/core/dataarray.py:454) coords, dims = _infer_coords_and_dims(data.shape, coords, dims)
    [455](file:///C:/Users/estev/AppData/Local/Programs/Python/Python39/lib/site-packages/xarray/core/dataarray.py:455) variable = Variable(dims, data, attrs, fastpath=True)
    [457](file:///C:/Users/estev/AppData/Local/Programs/Python/Python39/lib/site-packages/xarray/core/dataarray.py:457) if not isinstance(coords, Coordinates):

File [c:\Users\estev\AppData\Local\Programs\Python\Python39\lib\site-packages\xarray\core\dataarray.py:168](file:///C:/Users/estev/AppData/Local/Programs/Python/Python39/lib/site-packages/xarray/core/dataarray.py:168), in _infer_coords_and_dims(shape, coords, dims)
    [166](file:///C:/Users/estev/AppData/Local/Programs/Python/Python39/lib/site-packages/xarray/core/dataarray.py:166) dims_tuple = tuple(dims)
    [167](file:///C:/Users/estev/AppData/Local/Programs/Python/Python39/lib/site-packages/xarray/core/dataarray.py:167) if len(dims_tuple) != len(shape):
--> [168](file:///C:/Users/estev/AppData/Local/Programs/Python/Python39/lib/site-packages/xarray/core/dataarray.py:168)     raise ValueError(
    [169](file:///C:/Users/estev/AppData/Local/Programs/Python/Python39/lib/site-packages/xarray/core/dataarray.py:169)         "different number of dimensions on data "
    [170](file:///C:/Users/estev/AppData/Local/Programs/Python/Python39/lib/site-packages/xarray/core/dataarray.py:170)         f"and dims: {len(shape)} vs {len(dims_tuple)}"
    [171](file:///C:/Users/estev/AppData/Local/Programs/Python/Python39/lib/site-packages/xarray/core/dataarray.py:171)     )
    [172](file:///C:/Users/estev/AppData/Local/Programs/Python/Python39/lib/site-packages/xarray/core/dataarray.py:172) for d in dims_tuple:
    [173](file:///C:/Users/estev/AppData/Local/Programs/Python/Python39/lib/site-packages/xarray/core/dataarray.py:173)     if not hashable(d):

ValueError: different number of dimensions on data and dims: 1 vs 2
```

I managed to solve the second error by adding `dtype=object` to `np.array(parameters_ts,dtype=object)`. However, the first error prevents me from executing the cell.

Some information that might help:
`xarray 2024.3.0`
`numpy 1.23.5`

Thanks again!

**Comment by ThGaskin** [comment]
I can't reproduce the error, which is however weird since I should be getting the errors you are (generating a `np.array` from a list of lists/arrays should throw a warning at least) -- odd. I'm now using `stack` in the notebook, which should work -- see if that helps?

Best, 

Thomas

**Comment by estevaofuzaro98** [comment]
I managed to get it to work by carrying out the following process:
```python
param_p = []
param_t = []

for tensor in parameters_pt:
    param_p.append(tensor[0].item())
    param_t.append(tensor[1].item())
```

After that I plotted them normally using matplotlib directly:
```python
plt.figure(figsize=(8, 7))
plt.plot(param_p, label='p_infect')
plt.plot(param_t, label='t_infectious')
plt.xlabel('epoch')
plt.tight_layout()
plt.legend()
plt.show()
```

I ended up not using the xarray library at all and got the following result for 500 epochs, for example:
<img src="https://github.com/ThGaskin/NeuralABM/assets/82242138/0f80040b-398d-4977-87cd-e88887f5dec5" width="700">

Thank you very much for your support! It's much clearer how the calibration process works. 😁

**Comment by ThGaskin** [comment]
So everything works now as it is in the latest commit?

**Comment by estevaofuzaro98** [comment]
Yes, perfectly! I'm going to close the issue. Thanks again @ThGaskin 🙏🏻🎉
