### ISSUE TITLE
no utopya_output directory

### ISSUE THREAD

**Issue by Zaaccckkkk** [ThGaskin/NeuralABM#62]
Hi,

I am an undergraduate at Imperial who try to do some research based on your paper. I am under the supervision of Dr. Pavliotis.

Just trying to understand your excellent work. 
I did not seem to see the "utopya_output directory" that you mentioned at "How to run a model" section. Do you know where I can find it and see the plots generated?

Regards,
Zhentian Wu

**Comment by ThGaskin** [comment]
Hi Zhentian, 

good to hear from you. The output directory by default is located in your home directory (usually `/Users/<user_name>`). You can change this by adding a `paths` entry to your run configuration (see the README). Let me know if it works

**Comment by Zaaccckkkk** [comment]
Hi,

Yes! This does solve my problem.
Thank you.

Regards,
Zhentian Wu
