### ISSUE TITLE
Parameter sweeping

### ISSUE THREAD

**Issue by Zaaccckkkk** [ThGaskin/NeuralABM#64]
Hi Thomas,

Just notice for SIR model, the true data for `kind=infected` plot in `density_from_joint.pdf` has different peaks (>0.8 and <0.4) before and after the parameter sweeping. (I see that maybe because you generate two synthetic data differently? The ">0.8" one follows `SIR_cfg.yml` and the "<0.4" one follows `data/SIR/ABM_data/data/uni0/config.yml`?) If so, why do you generate two synthetic datasets differently?

Also, although I said last time that SIR model for the Berlin data works well, it seems something went wrong when I tried to sweep `utopya run SIR --cs Predictions_on_ABM_data && utopya run SIR models/SIR/SIR_run_specific.yml`.  ( I changed the data load  directory in `SIR/cfgs/Predictions_on_ABM_data/run.yml`)   

Last question: I am not quite confident when directly using the Berlin data into the SIR model, since it has so many states(S, I, R, SY, H, Q ...). How do my SIR model knows which part of the Berlin data to use when I simply say `utopya run SIR models/SIR/SIR_run_specific.yml`?

**Comment by ThGaskin** [comment]
Hi, 

Q1: can you tell me what exactly command you are running?

Q2: I would need to see the config and the error output, 'something went wrong' isn't very helpful :D

Q3: yes, running the Berlin data with the SIR data wouldn't work directly, since the compartments are different. You will need to modify the code ...

**Comment by Zaaccckkkk** [comment]
Hi,

Q1: I run `utopya run SIR` and `utopya run SIR --cs Predictions_from_ABM_data`, and get the two set of plots as you did in the README. I notice the difference between the true data (the yellow line). Is it because of the reason I mentioned above? If so, why do you generate two synthetic datasets differently?

Q2/Q3: Alright, then I take back the "works well" part, cuz I did not modify the code! ( Could you give me some hints on how to modify it?) I think I can understand the structure of the whole Neural network and .yml files, but I haven't looked into the .py files.

**Comment by ThGaskin** [comment]
`utopya run SIR` and `utopya run SIR --cs Predictions_from_ABM_data` runs the model with different datasets; if you just run the default model (first command), synthetic data will be generated using the settings in the `SIR_cfg.yml` file. If you run the configuration set, the model will be trained on the data as given in the `Predictions_from_ABM_data/run.yml` file.

Q2: what are you trying to do? You're trying to run the SIR model with the Berlin data? Then I think you will first need to think about which compartments from the Berlin data you want to use, and then change the Berlin data into a data format that the SIR model can read -- so something like the `ABM_data`. The data is loaded in `DataGeneration.py` -- you can also modify this code to just load `.csv` files and convert them into a tensor, if you like. This is probably easiest for your purposes.

**Comment by Zaaccckkkk** [comment]
Q1: Okay great. So I understand it right. 
<img width="1048" alt="截屏2024-05-30 21 44 58" src="https://github.com/ThGaskin/NeuralABM/assets/116949883/17cdbc9e-4846-42a2-8a2d-cb69675088b4">
As this screenshot suggested, the datasets are generated using different N, r_infectious and t_infectious values. May I know why you need to use a different synthetic data?

**Comment by ThGaskin** [comment]
It’s just to illustrate different configurations …. you can modify the settings to whatever you like. The settings in the default config (`SIR_cfg.yml`) are the default settings that I wouldn’t change. Just change the ones you want to update in a run configuration

On 30 May 2024, at 23:02, Zaaccckkkk ***@***.***> wrote:



Q1: Okay great. So I understand it right.
2024-05-30.21.44.58.png (view on web)<https://github.com/ThGaskin/NeuralABM/assets/116949883/17cdbc9e-4846-42a2-8a2d-cb69675088b4>
As this screenshot suggested, the datasets are generated using different N, r_infectious and t_infectious values. May I know why you need to use a different synthetic data?

**Comment by Zaaccckkkk** [comment]
Gotcha!

**Comment by Zaaccckkkk** [comment]
Q2: Generally, my final goal is to use Neural network calibration on different models for a single SIR-related dataset(like the Berlin dataset) to see which model is more suitable for this specific dataset. (If I keep all the hyperparameters, optimizer, activation func.. the same, then better Neural network results should indicate, to some extent, more suitable models,right?)

So I decide to do a trial on Berlin data.

Thanks for your hints! I see that ABM_data/config contains 10 .yml files, do you know any source where I can learn such data construction?

**Comment by ThGaskin** [comment]
You mean where can you learn yaml? Google ‘yaml’, there will be plenty of documentation online

On 30 May 2024, at 23:13, Zaaccckkkk ***@***.***> wrote:



Q2: Generally, my final goal is to use Neural network calibration on different models for a single SIR-related dataset(like the Berlin dataset) to see which model is more suitable for this specific dataset. (If I keep all the hyperparameters, optimizer, activation func.. the same, then better Neural network results should indicate, to some extent, more suitable models,right?)

So I decide to do a trial on Berlin data.

Thanks for your hints! I see that ABM_data/config contains 10 .yml files, do you know any source where I can learn such data construction?

**Comment by Zaaccckkkk** [comment]
Thanks!
